name: '@narkdown/render-with-ejs'

description: Render markdown with the given ejs template.

branding:
  icon: arrow-down
  color: white

inputs:
  template-file-path:
    description: EJS template file path.
    required: false
    default: template.md
  target-file-path:
    description: Target markdown file path.
    required: false
    default: README.md
  data:
    description: Data to be used to render ejs templates.
    required: false

runs:
  using: 'node12'
  main: 'dist/index.js'
